// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

var TableNames = struct {
	GroupMembers string
	Groups       string
	Users        string
}{
	GroupMembers: "group_members",
	Groups:       "groups",
	Users:        "users",
}
