

/* Create Tables */

CREATE TABLE GROUPS
(
	ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
	NAME VARCHAR(255) NOT NULL COMMENT '名前',
	CREATED_AT DATETIME NOT NULL COMMENT '登録日時',
	CREATED_BY VARCHAR(64) NOT NULL COMMENT '登録トレース',
	UPDATED_AT DATETIME NOT NULL COMMENT '更新日時',
	UPDATED_BY VARCHAR(64) NOT NULL COMMENT '更新トレース',
	PRIMARY KEY (ID)
) COMMENT = 'グループ';


CREATE TABLE GROUP_MEMBERS
(
	ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
	IS_ADMIN BOOLEAN NOT NULL COMMENT '管理者か',
	USER_ID BIGINT UNSIGNED NOT NULL COMMENT 'user_id',
	GROUP_ID BIGINT UNSIGNED NOT NULL COMMENT 'グループID',
	CREATED_AT DATETIME NOT NULL COMMENT '登録日時',
	CREATED_BY VARCHAR(64) NOT NULL COMMENT '登録トレース',
	UPDATED_AT DATETIME NOT NULL COMMENT '更新日時',
	UPDATED_BY VARCHAR(64) NOT NULL COMMENT '更新トレース',
	PRIMARY KEY (ID)
) COMMENT = 'グループメンバー';


CREATE TABLE USERS
(
	ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
	NAME VARCHAR(255) NOT NULL COMMENT '名前',
	BIRTHDATE DATE COMMENT '誕生日',
	GENDER VARCHAR(10) NOT NULL COMMENT '性別 : 男: male
女: female',
	CREATED_AT DATETIME NOT NULL COMMENT '登録日時',
	CREATED_BY VARCHAR(64) NOT NULL COMMENT '登録トレース',
	UPDATED_AT DATETIME NOT NULL COMMENT '更新日時',
	UPDATED_BY VARCHAR(64) NOT NULL COMMENT '更新トレース',
	PRIMARY KEY (ID)
) COMMENT = 'users';



/* Create Foreign Keys */

ALTER TABLE GROUP_MEMBERS
	ADD CONSTRAINT FK_GROUP_MEMBERS_GROUPS FOREIGN KEY (GROUP_ID)
	REFERENCES GROUPS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE GROUP_MEMBERS
	ADD CONSTRAINT FK_GROUP_MEMBERS_USERS FOREIGN KEY (USER_ID)
	REFERENCES USERS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



